### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'datasets\MPIIFaceGaze\p00.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by Kelly-ZH** [hysts/pytorch_mpiigaze#25]
Hello, I have run the code with the instruction "python tools/preprocess_mpiifacegaze.py --dataset datasets/MPIIFaceGaze -o datasets/", and I had some problems, could you please help me to solve it ? Thank you very much.
`Traceback (most recent call last):
  File "tools/preprocess_mpiifacegaze.py", line 51, in <module>
    main()
  File "tools/preprocess_mpiifacegaze.py", line 47, in main
    add_mat_data_to_hdf5(person_id, dataset_dir, output_path)
  File "tools/preprocess_mpiifacegaze.py", line 13, in add_mat_data_to_hdf5
    with h5py.File(dataset_dir / f'{person_id}.mat', 'r') as f_input:
  File "E:\Anaconda\envs\mpiigaze\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "E:\Anaconda\envs\mpiigaze\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'datasets\MPIIFaceGaze\p00.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

**Comment by hysts** [comment]
Hi, @Kelly-ZH 

Sorry, the dataset path in README.md was wrong, and I fixed it. Thanks for reporting this.

**Comment by LiuZiMing000** [comment]
Hello, I run python tools/preprocess_mpiifacegaze.py --dataset datasets/MPIIFaceGaze -o datasets/ will report, Unable to open file (unable to open file: name ='datasets\MPIIFaceGaze\p00.mat', errno = 2 , error message ='No such file or directory', flags = 0, o_flags = 0) wrong, what is going on, I hope you can answer, thank you.
