### ISSUE TITLE
AttributeError: Can't pickle local object '_create_mpiifacegaze_transform.<locals>.<lambda>'

### ISSUE THREAD

**Issue by w359405949** [hysts/pytorch_mpiigaze#53]
[2021-11-24 21:59:34] __main__ INFO: Val 0
Traceback (most recent call last):
  File "E:\pytorch_mpiigaze\train.py", line 182, in <module>
    main()
  File "E:\pytorch_mpiigaze\train.py", line 160, in main
    validate(0, model, loss_function, val_loader, config,
  File "E:\pytorch_mpiigaze\train.py", line 91, in validate
    for step, (images, poses, gazes) in enumerate(val_loader):
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_create_mpiifacegaze_transform.<locals>.<lambda>'
PS E:\pytorch_mpiigaze> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\w\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

==============================================

does the MPIIFaceGaze dataset preprocessed?
run train.py with origin MPIIFaceGaze will throw above exceptions.

**Comment by hysts** [comment]
Hi, @w359405949 

I'm not sure what is causing the error, but anyway, you need to run [this](https://github.com/hysts/pytorch_mpiigaze#mpiifacegaze) to preprocess the dataset.

**Comment by w359405949** [comment]
@hysts thx.
